 meta_product_name: "ExploreLog"
 meta_title: "ExploreLog - Memories made simple"
 meta_description: "Comprehensive journey tracking and documentation mobile app"
 meta_image: "homepage.png" # should exist in `app/assets/images/`
